증가하는 전기자동차 추세에 따른 정책 제시
==
### <u>'무선 충전도로'와 '지역별 전기충전소'에 대한 최적화(Optimization)</u>
### [목차]

### 0. 주제 선정 이유
    - 전기차 증가에 따른 충전 인프라 확충 문제 발생


### 1. 분석 및 시각화
    - 무선 충전도로 설치 (최적화)
    - 서울시 전기 충전소 확충 (최적화)

### 2.  코드
    - Import
    - EDA & Preprocessing
    - Visualization(PyeChart)
### 3. 출처

## <br><br>0. Introduction

<img src = Demand.jpg width="400" height="400" align= "left">

### 점점 "늘어나는" 전기차 현황 <br>

세계적인 흐름과 동일하게 국내에서도 전기차가 차지하는 비중이 점차 늘어갈 전망이다. 정부의 친환경차보급로드맵에 따르면 국내 역시 전기차 보급이 점차 늘어날 것으로 예상된다. 2013년 산업수요 대비 비중이 0%였던 전기차는 올해 2.4%까지 비중을 늘릴 예정이고, 2025년에는 약 25만대를 보급해 산업수요에서 차지하는 비중을 14.4%까지 끌어올린다는 목표다. 국내 역시 빠른 속도로 전기차 시장이 성장하고 있는 것이다.

<img src = EVcharger.jpg width="300" height="400" align= "left">

...<br>
문제는 전기차 충전 인프라가 여전히 부족하다는 점이다. 지난해 우리나라의 전기차 충전기는 6만4188대로 등록된 전기차 13만4962대의 절반 수준에 불과하다. 정부는 공공용 급속 충전기를 확대하는 등 전기차 관련 인프라를 구축하는 데 전력을 기울이고 있지만 충전기 부족 문제는 당분간 해소하기 어려울 듯하다. 급속 충전기 늘리는 것만으로는 충전 인프라 확대 효과가 나타나지 않을 공산이 크다.<br>
...

출처 : 더스쿠프(http://www.thescoop.co.kr)

### Project의 목적

- 늘어가는 전기차에 맞춰 효율적으로 충전 인프라를 설치하는 방법을 탐색
- 주행거리가 상대적으로 적은 전기차를 효율적으로 충전을 할 수 있고, 배터리가 방전되서 일어나는 사고를 사전에 방지하기 위한 대안들을 탐색

## 1. 분석 및 시각화
### 1-1. 무선 충전도로 설치
<br>

- ### 무선 충전도로란?

     무선 충전도로는 말그대로 달리기만 해도 배터리가 충전되는 도로로, 도로 아래에 묻어 놓은 구리 송전 코일에 전기가 흐르면 전기차에 장착된 전자기 유도 충전 시스템이 이를 끌어들여 배터리로 연결함으로써 충전이 되는 것이다. 이런 충전 인프라는 전기차가 가진 충전 문제를 근본적으로 해결해 줄 수 있는데, <u>**별도로 충전을 하지 않아도 지속적으로 전력을 도로에서 공급받을 수 있으므로 주행할 수 있는 거리도 훨씬 더 길어지게 된다**.</u> 도로를 달릴 때 충전이 된다면 충전소에서 낭비해야 하는 <u>**시간을 절약할 수 있다.**</u> 특히 오랜 시간 동안 먼 거리를 운행해야 하는 트럭이나 고속버스 같은 경우는 이런 도로만 등장한다면 즉시 전기트럭이나 전기버스로 변신할 수 있다. 이 뿐만이 아니라 주행 중에 무선충전을 할 수 있다는 것은 <u>**배터리 용량을 대폭 줄일 수 있다는 의미다.**</u> 배터리 용량은 크기 및 무게와 밀접한 연관이 있기 때문에 <u>**전기차 중량도 함께 감소하게 되므로 연비를 개선하는 효과를 누릴 수 있다.**</u>
<br>


<br>  무선 충전도로는 자동차의 속도가 빠를수록 효율이 좋으므로, 우선적으로 고속도로에 대한 분석을 실시하였으며 최대한 많은 차들이 혜택을 누릴 수 있게 교통량이 많은 3개의 고속도로를 선정하였습니다.

In [2]:
IFrame(src="https://datanyang.github.io/yearly_traffic.html", width="100%", height="600px")

경부선, 서울외곽선, 영동선의 연간 통행량이 가장 많아 3개 고속도로에 대한 5개년 무선충전도로를 설치하고자 하였다.

In [3]:
IFrame(src="https://datanyang.github.io/Top3.html", width="100%", height="380px")

고속도로별 각 구간들의 교통량을 비교하면 위와 같이 나온다. 이 데이터에 기반하여 **각 연도별로 어떤 도로의 어떤 구간에** 무선 충전도로를 먼저 설치할지 최적화를 진행하였다. (진행 코드는 목차 2. EDA & Preprocessing에 나와있다.)

<img src = h_formulation.png width="900" height="800">

목적식은 **교통량이 많은 도로들의 설치 길이를 최대화**하는 것이고, 무선 충전도로 설치비용은 1km당 13.5억원, 그에 대한 예산은 5179억원이라는 기준을 가지고 식을 진행하였다.

5년동안 무선충전도로 사업을 진행하였을 때 각 구간별 설치 길이는 다음과 같이나온다.

In [4]:
IFrame(src="https://datanyang.github.io/progress.html", width="100%", height="450px")

In [5]:
IFrame(src="https://datanyang.github.io/highway_1.html", width="100%", height="600px")

In [6]:
IFrame(src="https://datanyang.github.io/highway_2.html", width="100%", height="600px")

In [7]:
IFrame(src="https://datanyang.github.io/highway_3.html", width="100%", height="600px")

In [8]:
IFrame(src="https://datanyang.github.io/highway_4.html", width="100%", height="600px")

In [9]:
IFrame(src="https://datanyang.github.io/highway_5.html", width="100%", height="600px")

각 연도별로 무선 충전 도로 설치 현황을 나타내었다. 설명을 덧붙이자면 지도에서 검은색은 설치가 완료된 도로, 빨간색은 그 해에 공사가 진행되는 도로, 주황색은 일부만 설치되어 다음 년도에도 진행되어야 하는 도로, 초록색은 무선 충전도로가 아닌 일반 고속도로이다.
> 이 프로젝트가 끝난 뒤 고속도로 현황  
> - 경부선 : 18.52%의 완공률, 3.7%의 진행률
> - 서울외곽선 : 78.79%의 완공률, 18.18%의 진행률
> - 영동선 : 21.21%의 완공률, 6.06%의 진행률<br>

교통량이 가장 부하되는 수도권을 중심으로 무선충전 고속도로가 먼저 설치되고 있음을 알 수 있다. 5년차에 들어서는 서울외곽순환고속도로 대부분이 무선충전 인프라가 마련됨을 볼 수 있다.

### 1-2. 서울시 전기 충전소 확충

- 서울시 전기 충전소 현황

In [10]:
IFrame(src="https://datanyang.github.io/ev_charger.html", width="100%", height="450px")

이번 프로젝트는 서울시 생활인구를 기준으로 **[구별 생활인구수/전기 충전소 수]**를 기준으로 분석을 진행하였다. 생활인구수를 기준으로 잡은 이유는 **실제로 시민들이 그 시간대에 어디에 위치하는 지**를 파악하여 어디에 충전소를 설치하여야 실용적인 도움이 되는지 파악하기 위해서이다. 또한 **시민들이 일하는 낮(09~18), 시민들이 집에 머무는 밤(18-09) 2가지 시간대**로 나누었으며, 이렇게 나눈 이유는 전기차는 보통 단시간에 충전이 불가능하기 때문에 회사에 상주하는 동안 또는 집에 머무는 동안 전기차를 충전시키기 때문이다.

- 현재 서울시의 전기차 충전소 현황

In [11]:
IFrame(src="https://datanyang.github.io/viz_noon_0.html", width="100%", height="600px")

In [12]:
IFrame(src="https://datanyang.github.io/viz_night_0.html", width="100%", height="600px")

낮은 연두색 계열로, 밤은 보라색 계열로 표시하였으며 색깔이 **진할수록 전기 충전소 1대당 감당하는 인구 수가 많다.**

최적화에 들어가기 앞서 낮과 밤을 분리해서 충전소를 설치할 수는 물리적으로 불가능하기 때문에 낮과 밤에 가중치를 두어서 인구를 종합하는 방향으로 진행하였다. 다음은 낮과 밤의 가중치를 구하기 위하여 사용한 데이터이다.

In [13]:
IFrame(src="https://datanyang.github.io/power_demand.html", width="100%", height="450px")

보통 낮 시간대의 충전량이 밤시간대의 충전량보다 많음을 알 수 있다.
- 낮 : 0.687, 밤 : 0.313
- 가중치를 구하는 방법은 2. EDA&Preprocessing에 자세히 나와있다.

이 가중치를 각각 낮 시간대별 생활인구 수, 밤 시간대별 생활인구 수에 곱한 후, 더하여 최종 생활인구 지표로 사용하였다. 이 데이터들을 기반으로 최적화를 진행하였다. (진행 코드는 목차 2. EDA & Preprocessing에 나와있다.)

<img src = e_formulation.png width="900" height="800">

목적식은 인구가 많은 행정구의 설치할 충전소 수를 최대화하는 것이고, 전기 충전소 설치비용은 1km당 1400만원, 그에 대한 예산은 26.9억원이라는 기준을 가지고 식을 진행하였다.

5년동안 서울시 전기 충전소로 확충 사업을 진행하였을 때 각 행정구별 **충전소 1대당 감당하는 인구 수**는 다음과 같이나온다.

In [14]:
IFrame(src="https://datanyang.github.io/pop_per_charger.html", width="100%", height="450px")

- 1년도 진행상황

In [15]:
IFrame(src="https://datanyang.github.io/viz_noon_1.html", width="100%", height="600px")

In [17]:
IFrame(src="https://datanyang.github.io/viz_night_1.html", width="100%", height="600px")

- 2년도 진행상황

In [18]:
IFrame(src="https://datanyang.github.io/viz_noon_2.html", width="100%", height="600px")

In [19]:
IFrame(src="https://datanyang.github.io/viz_night_2.html", width="100%", height="600px")

- 3년도 진행상황

In [20]:
IFrame(src="https://datanyang.github.io/viz_noon_3.html", width="100%", height="600px")

In [21]:
IFrame(src="https://datanyang.github.io/viz_night_3.html", width="100%", height="600px")

- 4년도 진행상황

In [22]:
IFrame(src="https://datanyang.github.io/viz_noon_4.html", width="100%", height="600px")

In [23]:
IFrame(src="https://datanyang.github.io/viz_night_4.html", width="100%", height="600px")

- 5년도 진행상황

In [24]:
IFrame(src="https://datanyang.github.io/viz_noon_5.html", width="100%", height="600px")

In [25]:
IFrame(src="https://datanyang.github.io/viz_night_5.html", width="100%", height="600px")

인구 수가 많은 강남구, 송파구를 시작으로 하여 관악구, 영등포구, 마포구, 강동구, 동작구, 중구의 전기충전소 부담이 줄어든 것을 확인 할 수 있다.

### 요약 정리

<img src = conclusion.jpg width="900" height="800">

## 2. Code

### 2-1. Import

In [26]:
import gurobipy as gp
from gurobipy import GRB
import pandas as pd
import folium
from folium import Choropleth, Circle, Marker
from folium.plugins import HeatMap, MarkerCluster
import numpy as np
import requests, bs4
from lxml import html
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus, unquote
import os
from mapboxgl.utils import (
    create_numeric_stops,
    create_color_stops
)
from mapboxgl.utils import df_to_geojson    
from mapboxgl.viz import *
import sys
from IPython.display import IFrame
from pyecharts import Bar, Pie, Timeline, Style, Grid

### 2-2. EDA & Preprocessing

In [27]:
pd.set_option('display.max.colwidth', 10)

### 무선 충전도로 설치 
경부선, 서울외곽선, 영동선 3개의 고속도로 데이터를 처리하는 구간입니다.

In [28]:
Top = pd.read_excel('Top.xlsx')
Top = Top[['구간', '연장(km)', '차로수', '계']]
Top.head(10)

          구간  연장(km)  차로수      계
0  구서IC-노포IC     5.1    6  71512
1  노포IC-노...     0.5    6  66817
2  노포JCT-...     7.3    6  86906
3  양산JCT-...     5.1    8  89018
4  양산IC-통...    12.8    6  71192
5  통도사하이패...     1.4    6  68352
6  통도사IC-...     6.4    6  65305
7  서울산IC-...     1.5    6  58585
8  언양JCT-...    17.2    4  49423
9  활천IC-경주IC    10.9    4  45602

위의 3개의 고속도로의 각 구간에 대해서 **최적화**를 진행하는 코드입니다. 총 5번 진행이 됩니다.

In [29]:
def optimize(Top) :
    try:

        # Create a new model
        m = gp.Model("qp")

        # Create variables
        for i in range(1, len(Top)+1):
            globals()['x_%d'%i] = m.addVar(vtype=GRB.BINARY, name="x_%d"%i)
            globals()['y_%d'%i] = m.addVar(vtype=GRB.CONTINUOUS, name="y_%d"%i)
        for i in range(len(Top)):
            globals()['l_%d'%(i+1)] = Top.loc[i, '연장(km)']
            globals()['n_%d'%(i+1)] = Top.loc[i, '차로수']
            globals()['e_%d'%(i+1)] = Top.loc[i, '계']

        # Set objective
        obj = None
        for i in range(1, len(Top)+1):
            obj += globals()['x_%d'%i] * globals()['y_%d'%i] * globals()['e_%d'%i]
        m.setObjective(obj, GRB.MAXIMIZE)

        const = None
        for i in range(1, len(Top)+1):
            const +=  globals()['x_%d'%i] * globals()['y_%d'%i] * globals()['n_%d'%i]
        # Add constraint: x + 2 y + 3 z <= 4
        m.addConstr(13.5 * const <= 5179, "c0")
        
        
        # Add constraint: x + y >= 1
        for i in range(1, len(Top)+1):
            m.addConstr(globals()['y_%d'%i] <= globals()['l_%d'%i], "c_%d"%i)

        # Optimize model
        m.optimize()

        print('Obj: %g' % m.objVal)
        return m

    except gp.GurobiError as e:
        print('Error code ' + str(e.errno) + ': ' + str(e))
        return None

    except AttributeError:
        print('Encountered an attribute error')
        return None

In [30]:
# Optimizing
project_year = 5
tmp = pd.DataFrame(data = [], columns = list(set(Top.columns).union(set(['year']))))
year = 2022
next_year = []
for i in range(project_year):
    m = optimize(Top)
    lst = [] 
    for v in m.getVars() :
        if "y" in v.varName :
            if v.x > 0 :
                lst.append(int(v.varName.split('_')[1])-1)
    a = Top.loc[lst,]
    a['year'] = year
    year += 1
    tmp = pd.concat([a, tmp])
    tmp2 = []
    for i in lst :
        if Top.iloc[i,1] != globals()['y_%d'%(i+1)].x :
            Top.iloc[i,1] -= globals()['y_%d'%(i+1)].x
            tmp2.append(Top.iloc[i,:])
            lst.remove(i)
    next_year.append(tmp2)
    Top.drop(index = lst, inplace = True)
    Top.reset_index(drop=True, inplace= True)
    Top.to_csv('./Restopt{}.csv'.format(i))
tmp

Academic license - for non-commercial use only - expires 2022-07-23
Using license file C:\Users\USER\gurobi.lic
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 120 rows, 240 columns and 120 nonzeros
Model fingerprint: 0xe78a2b7c
Model has 120 quadratic objective terms
Model has 1 quadratic constraint
Variable types: 120 continuous, 120 integer (120 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [5e+01, 1e+02]
  Objective range  [0e+00, 0e+00]
  QObjective range [5e+04, 5e+05]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e-01, 2e+01]
  QRHS range       [5e+03, 5e+03]
Found heuristic solution: objective -0.0000000
Presolve removed 120 rows and 0 columns
Presolve time: 0.00s
Presolved: 361 rows, 360 columns, 960 nonzeros
Variable types: 240 continuous, 120 integer (120 binary)

Root relaxation: objective -1.015894e+07, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0    1.015894e+07 1.0159e+07  0.00%     -    0s

Explored 1 nodes (1 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 1.01589e+07 -0

Optimal solution found (tolerance 1.00e-04)
Best objective 1.015894345000e+07, best bound 1.015894345000e+07, gap 0.0000%
Obj: 1.01589e+07
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 108 rows, 216 columns and 108 nonzeros
Model fingerprint: 0x70604b7b
Model has 108 quadratic objective terms
Model has 1 quadratic constraint
Variable types: 108 continuous, 108 integer (108 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [5e+01, 1e+02]
  Objective range  [0e+00, 0e+00]
  QObjective range [5e+04, 4e+05]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e-01, 2e+01]
  QRHS range       [5e+03, 5e+03]
Found heuristic solution: objective -0.0000000
Presolve removed 108 rows and 0 columns
Presolve time: 0.00s
Presolved: 325 rows, 324 columns, 864 nonzeros
Variable types: 216 continuous, 108 integer (108 binary)

Root relaxation: objective -8.568853e+06, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0    8568853.2500 8568853.25  0.00%     -    0s

Explored 1 nodes (1 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 8.56885e+06 -0

Optimal solution found (tolerance 1.00e-04)
Best objective 8.568853250000e+06, best bound 8.568853250000e+06, gap 0.0000%
Obj: 8.56885e+06
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 94 rows, 188 columns and 94 nonzeros
Model fingerprint: 0xcb34b732
Model has 94 quadratic objective terms
Model has 1 quadratic constraint
Variable types: 94 continuous, 94 integer (94 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [5e+01, 1e+02]
  Objective range  [0e+00, 0e+00]
  QObjective range [5e+04, 4e+05]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e-01, 2e+01]
  QRHS range       [5e+03, 5e+03]
Found heuristic solution: objective -0.0000000
Presolve removed 94 rows and 0 columns
Presolve time: 0.00s
Presolved: 283 rows, 282 columns, 752 nonzeros
Variable types: 188 continuous, 94 integer (94 binary)

Root relaxation: objective -7.785097e+06, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0    7785096.8333 7785096.83  0.00%     -    0s

Explored 1 nodes (1 simplex iterations) in 0.03 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 7.7851e+06 -0

Optimal solution found (tolerance 1.00e-04)
Best objective 7.785096833333e+06, best bound 7.785096833333e+06, gap 0.0000%
Obj: 7.7851e+06
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 85 rows, 170 columns and 85 nonzeros
Model fingerprint: 0x112e7171
Model has 85 quadratic objective terms
Model has 1 quadratic constraint
Variable types: 85 continuous, 85 integer (85 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [5e+01, 1e+02]
  Objective range  [0e+00, 0e+00]
  QObjective range [5e+04, 4e+05]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e-01, 2e+01]
  QRHS range       [5e+03, 5e+03]
Found heuristic solution: objective -0.0000000
Presolve removed 85 rows and 0 columns
Presolve time: 0.00s
Presolved: 256 rows, 255 columns, 680 nonzeros
Variable types: 170 continuous, 85 integer (85 binary)

Root relaxation: objective -7.348395e+06, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0    7348395.1481 7348395.15  0.00%     -    0s

Explored 1 nodes (1 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 7.3484e+06 -0

Optimal solution found (tolerance 1.00e-04)
Best objective 7.348395148148e+06, best bound 7.348395148148e+06, gap 0.0000%
Obj: 7.3484e+06
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 77 rows, 154 columns and 77 nonzeros
Model fingerprint: 0x5dad1eb5
Model has 77 quadratic objective terms
Model has 1 quadratic constraint
Variable types: 77 continuous, 77 integer (77 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [5e+01, 1e+02]
  Objective range  [0e+00, 0e+00]
  QObjective range [5e+04, 4e+05]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e-01, 2e+01]
  QRHS range       [5e+03, 5e+03]
Found heuristic solution: objective -0.0000000
Presolve removed 77 rows and 0 columns
Presolve time: 0.00s
Presolved: 232 rows, 231 columns, 616 nonzeros
Variable types: 154 continuous, 77 integer (77 binary)

Root relaxation: objective -6.891600e+06, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0    6891600.2111 6891600.21  0.00%     -    0s

Explored 1 nodes (1 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 6.8916e+06 -0

Optimal solution found (tolerance 1.00e-04)
Best objective 6.891600211111e+06, best bound 6.891600211111e+06, gap 0.0000%
Obj: 6.8916e+06

           구간     연장(km) 차로수       계  year
17  북대구IC-...   5.500000   8  144977  2026
43  금토JCT-...   6.800000  10  181871  2026
44  강일IC-토평IC   1.300000   8  140100  2026
45  안현JCT-...   4.800000   8  142884  2026
46  산본IC-평촌IC   4.100000   8  136274  2026
48  별내IC-의...   8.000000   8  141331  2026
49  송추IC-통...   2.485185   8  148438  2026
50  통일로IC-...   6.000000   8  147078  2026
54  북수원IC-...   6.100000   8  143044  2026
55  동수원IC-...   4.900000   8  139741  2026
42  천안JCT-...   6.700000   8  148557  2025
43  북천안IC-...  10.488889   8  157440  2025
47  일산IC-자...   2.200000  10  189032  2025
48  장수IC-시흥IC   4.200000   8  155771  2025
49  시흥IC-안...   2.700000   8  152620  2025
51  조남JCT-...   5.300000   8  154501  2025
53  평촌IC-학...   2.900000   8  153431  2025
56  호원IC-송추IC   6.500000   8  154385  2025
57  송추IC-통...   8.900000   8  148438  2025
43  북천안IC-...  11.800000   8  157440  2024
44  안성JCT-...  13.300000   8  166623  2024
45  동탄JCT-...   5.100000   8  159599  2024
46  수원신갈IC...   2.700000  10  197800  2024
50  남양주IC-...   1.967593   8  166752  2024
51  구리IC-퇴...   2.800000   8  161442  2024
56  도리JCT-...   4.400000   8  162491  2024
60  학의JCT-...   8.800000   8  158708  2024
66  고양IC-일산IC   3.300000   8  161999  2024
70  안산JCT-...   4.800000   6  122552  2024
43  천안IC-북...   8.200000   8  180070  2023
45  안성IC-안...   4.800000   8  188440  2023
47  오산IC-동...   3.900000   8  169972  2023
52  성남IC-송파IC   5.300000   8  175490  2023
53  서하남IC-...   5.000000   8  174832  2023
55  토평IC-남...   2.400000   8  188115  2023
56  남양주IC-...   2.000000   8  166752  2023
59  김포IC-노...   2.246296   8  189513  2023
60  노오지JCT...   3.000000   8  170514  2023
71  의정부IC-...   1.600000   8  166803  2023
76  서창JCT-...   5.900000   6  137297  2023
79  서안산IC-...   3.300000   6  128843  2023
82  둔대JCT-...   1.700000   6  130577  2023
83  군포IC-동...   1.600000   6  135445  2023
84  부곡IC-북...   2.800000   6  137744  2023
49  기흥IC-수...   5.100000   8  211996  2022
51  신갈JCT-...  13.100000   8  201226  2022
54  판교JCT-...   4.200000   8  209014  2022
56  송파IC-서...   5.000000   8  202516  2022
58  하남JCT-...   2.600000   8  223519  2022
59  상일IC-강일IC   3.000000   8  239881  2022
65  자유로JCT...   3.100000   8  201740  2022
66  김포IC-노...   3.800000   8  189513  2022
68  계양IC-서...   2.300000   8  212076  2022
69  서운JCT-...   2.100000   8  253490  2022
70  중동IC-송내IC   2.000000   8  211004  2022
71  송내IC-장수IC   2.400000   8  230823  2022
95  동군포IC-...   2.000000   6  167272  2022

당시 년도에서 공사 마무리가 되지 않아(예산이 부족하여 설치한 길이가 모자름) 다음 년도로 넘기게 되는 도로들의 리스트입니다.

In [31]:
idx = 0
for e in next_year:
    a = e[0]
    if idx == 0:
        ny = pd.DataFrame(a).T
    else:
        ny = pd.concat([ny, pd.DataFrame(a).T])
    idx += 1
ny

           구간   연장(km) 차로수       계
66  김포IC-노...   2.2463   8  189513
56  남양주IC-...  1.96759   8  166752
43  북천안IC-...  10.4889   8  157440
57  송추IC-통...  2.48519   8  148438
46  산본IC-평촌IC  3.73148   8  136274

In [32]:
Top = pd.read_excel('Top.xlsx')
Top['지점번호'] = list(map(lambda x: int(x.split('-')[0]) if type(x)==type('1') else int(x), Top['지점번호']))

lst = []
num = []
for e in sorted(list(set(tmp['year']))):
    df = Top.merge(tmp[tmp['year']==e], how='inner', on=['구간', '연장(km)', '차로수', '계'])
    lst.append(list(map(lambda x: tuple(list(map(float, x.split('~')))),list(df['이정(km)']))))
    num.append(list(df['지점번호']))

ny = ny.merge(Top, how='inner', on=['구간','차로수','계'])

year = 2021
for i in range(len(lst)):
    year += 1
    if i == 0:
        Top = pd.DataFrame(np.array([list(map(lambda x: x[0], lst[i])), list(map(lambda x: x[1], lst[i])), num[i]]).T, columns=['이정_start','이정_end', '지점번호'])
        Top['연도'] = year
    else:
        tmp = pd.DataFrame(np.array([list(map(lambda x: x[0], lst[i])), list(map(lambda x: x[1], lst[i])), num[i]]).T, columns=['이정_start','이정_end', '지점번호'])
        tmp['연도'] = year
        Top = pd.concat([Top, tmp])

Top['지점번호'] = list(map(lambda x: 10 if 100 <= x < 1000 else 500 if 5000 <= x < 9999 else 1000, Top['지점번호']))

In [33]:
ny

,구간,연장(km)_x,차로수,계,지점번호,도명,시/군,읍/면,동/리,이정(km),연장(km)_y,승용차
0,김포IC-노...,2.2463,8,189513,10023,경기,김포,고촌,신곡,75.2~79,3.8,NaN
1,남양주IC-...,1.96759,8,166752,10009,경기,남양주,NaN,도농,28.8~30.8,2.0,NaN
2,북천안IC-...,10.4889,8,157440,132,충남,천안,입장,용정,347.5~...,11.8,113894.0
3,송추IC-통...,2.48519,8,148438,10028,경기,양주,장흥,삼하,51.7~60.6,8.9,NaN
4,산본IC-평촌IC,3.73148,8,136274,10013,경기,군포,NaN,산본,112.2~...,4.1,NaN

무선 충전도로가 설치되는 구간의 이정표의 시작과 끝, 어느 고속도로인지, 어느 년도에 공사가 진행되는지 나타내 주는 데이터프레임입니다.

In [34]:
Top.head(10)

   이정_start  이정_end  지점번호    연도
0     386.4   391.5    10  2022
1     394.2   407.3    10  2022
2       0.0     4.2  1000  2022
3       9.5    14.5  1000  2022
4      19.5    22.1  1000  2022
5      22.1    25.1  1000  2022
6      72.1    75.2  1000  2022
7      75.2    79.0  1000  2022
8      82.0    84.3  1000  2022
9      84.3    86.4  1000  2022

이정을 받아들여 색깔을 부여하는 코드입니다.

In [35]:
def add_categorical_legend(folium_map, title, colors, labels):
    if len(colors) != len(labels):
        raise ValueError("colors and labels must have the same length.")

    color_by_label = dict(zip(labels, colors))
    
    legend_categories = ""     
    for label, color in color_by_label.items():
        legend_categories += f"<li><span style='background:{color}'></span>{label}</li>"
        
    legend_html = f"""
    <div id='maplegend' class='maplegend'>
      <div class='legend-title'>{title}</div>
      <div class='legend-scale'>
        <ul class='legend-labels'>
        {legend_categories}
        </ul>
      </div>
    </div>
    """
    script = f"""
        <script type="text/javascript">
        var oneTimeExecution = (function() {{
                    var executed = false;
                    return function() {{
                        if (!executed) {{
                             var checkExist = setInterval(function() {{
                                       if ((document.getElementsByClassName('leaflet-top leaflet-right').length) || (!executed)) {{
                                          document.getElementsByClassName('leaflet-top leaflet-right')[0].style.display = "flex"
                                          document.getElementsByClassName('leaflet-top leaflet-right')[0].style.flexDirection = "column"
                                          document.getElementsByClassName('leaflet-top leaflet-right')[0].innerHTML += `{legend_html}`;
                                          clearInterval(checkExist);
                                          executed = true;
                                       }}
                                    }}, 100);
                        }}
                    }};
                }})();
        oneTimeExecution()
        </script>
      """
   

    css = """

    <style type='text/css'>
      .maplegend {
        z-index:9999;
        float:right;
        background-color: rgba(255, 255, 255, 1);
        border-radius: 5px;
        border: 2px solid #bbb;
        padding: 10px;
        font-size:12px;
        positon: relative;
      }
      .maplegend .legend-title {
        text-align: left;
        margin-bottom: 5px;
        font-weight: bold;
        font-size: 90%;
        }
      .maplegend .legend-scale ul {
        margin: 0;
        margin-bottom: 5px;
        padding: 0;
        float: left;
        list-style: none;
        }
      .maplegend .legend-scale ul li {
        font-size: 80%;
        list-style: none;
        margin-left: 0;
        line-height: 18px;
        margin-bottom: 2px;
        }
      .maplegend ul.legend-labels li span {
        display: block;
        float: left;
        height: 16px;
        width: 30px;
        margin-right: 5px;
        margin-left: 0;
        border: 0px solid #ccc;
        }
      .maplegend .legend-source {
        font-size: 80%;
        color: #777;
        clear: both;
        }
      .maplegend a {
        color: #777;
        }
    </style>
    """

    folium_map.get_root().header.add_child(folium.Element(script + css))

    return folium_map

모든도로의 각 구간별 이정

In [36]:
RSE = pd.read_csv("road2.csv", encoding='cp949')
RSE.head()

   노선번호  도로명   이정       X좌표값       Y좌표값  GRS80X좌표값  GRS80Y좌표값
0    10  경부선  0.0  35.246578  129.09...  390524...  296459...
1    10  경부선  0.1  35.247249  129.09...  390589...  296535...
2    10  경부선  0.2  35.247919  129.09...  390654...  296611...
3    10  경부선  0.3  35.248590  129.09...  390720...  296687...
4    10  경부선  0.4  35.249260  129.09...  390785...  296763...

영동선의 각 구간별 이정

In [37]:
yeongdong_line = RSE[RSE.노선번호 == 500]
yeongdong_line.head()

       노선번호  도로명   이정       X좌표값       Y좌표값  GRS80X좌표값  GRS80Y좌표값
31263   500  영동선  0.0  37.437852  126.73...  176960...  537638...
31264   500  영동선  0.1  37.436968  126.73...  176941...  537540...
31265   500  영동선  0.2  37.436084  126.73...  176921...  537442...
31266   500  영동선  0.3  37.435201  126.73...  176901...  537344...
31267   500  영동선  0.4  37.434317  126.73...  176881...  537246...

서울외곽선의 각 구간별 이정

In [38]:
seoul_line = RSE[RSE.노선번호 == 1000]
seoul_line.head()

       노선번호       도로명   이정       X좌표값       Y좌표값  GRS80X좌표값  GRS80Y좌표값
40414  1000  수도권제1순환선  0.0  37.405752  127.09...  208379...  534048...
40415  1000  수도권제1순환선  0.1  37.406091  127.09...  208472...  534085...
40416  1000  수도권제1순환선  0.2  37.406430  127.09...  208564...  534123...
40417  1000  수도권제1순환선  0.3  37.406768  127.09...  208657...  534161...
40418  1000  수도권제1순환선  0.4  37.407073  127.09...  208751...  534195...

경부선의 각 구간별 이정

In [39]:
gyungbu_line = RSE[RSE.노선번호 == 10]
gyungbu_line.head()

   노선번호  도로명   이정       X좌표값       Y좌표값  GRS80X좌표값  GRS80Y좌표값
0    10  경부선  0.0  35.246578  129.09...  390524...  296459...
1    10  경부선  0.1  35.247249  129.09...  390589...  296535...
2    10  경부선  0.2  35.247919  129.09...  390654...  296611...
3    10  경부선  0.3  35.248590  129.09...  390720...  296687...
4    10  경부선  0.4  35.249260  129.09...  390785...  296763...

교통량 3위 3개 고속도로의 구간별 이정

In [40]:
Line = pd.concat([yeongdong_line, seoul_line, gyungbu_line], axis = 0)

In [41]:
Line

       노선번호  도로명     이정       X좌표값       Y좌표값  GRS80X좌표값  GRS80Y좌표값
31263   500  영동선    0.0  37.437852  126.73...  176960...  537638...
31264   500  영동선    0.1  37.436968  126.73...  176941...  537540...
31265   500  영동선    0.2  37.436084  126.73...  176921...  537442...
31266   500  영동선    0.3  37.435201  126.73...  176901...  537344...
31267   500  영동선    0.4  37.434317  126.73...  176881...  537246...
...     ...  ...    ...        ...        ...        ...        ...
4221     10  경부선  422.6  37.517992  127.01...  201481...  546501...
4222     10  경부선  422.7  37.518826  127.01...  201519...  546593...
4223     10  경부선  422.8  37.519635  127.01...  201563...  546683...
4224     10  경부선  422.9  37.520507  127.01...  201586...  546780...
4225     10  경부선  423.0  37.521395  127.01...  201571...  546878...

[7851 rows x 7 columns]

지도에 각년도별 무선도로 설치 현황을 나타내주는 코드입니다.

In [42]:
def color_producer(val, road, year):
    global Top, ny
    
    status = 0
    
    orange = ny.iloc[year-2022, :]
    orange_val_range = list(map(float, list(orange['이정(km)'].split('~'))))
    
    if orange_val_range[0] <= val <= orange_val_range[1]:
        return 'orange'
        
    target = Top[Top['연도'] == year]
    for i in range(len(target)):
        if target.iloc[i,0] <= val <= target.iloc[i,1]:
            return 'red'
        
    target = Top[Top['연도'] < year]
    for i in range(len(target)):
        if target.iloc[i,0] <= val <= target.iloc[i,1]:
            return 'black'
    
    return 'forestgreen'
    
idx = 1
for n in range(2022, 2027):
    globals()["m_%d"%(idx)] = folium.Map(location=[37.2,127], tiles='cartodbpositron', zoom_start=9)
    globals()["m_%d"%(idx)] = add_categorical_legend(globals()["m_%d"%(idx)], 'Year ' + '%d'%(idx),
                                 colors = ['#000', '#FF0000', '#FF7F00', '#228B22'],
                               labels = ['Complete',  'Progressing', 'Carry Forward', 'None'])

    for i in range(0,len(Line)):
        Circle(
            location=[Line.iloc[i]['X좌표값'], Line.iloc[i]['Y좌표값']],
            radius=20,
            color=color_producer(Line.iloc[i]['이정'],Line.iloc[i]['노선번호'], n)).add_to(globals()["m_%d"%(idx)])
    
    idx += 1

In [69]:
m_5.save('highway_5.html')
m_4.save('highway_4.html')
m_3.save('highway_3.html')
m_2.save('highway_2.html')
m_1.save('highway_1.html')

### 서울시 지역별 전기 충전소 확충
서울시 전기충전소 현황 불러오기

In [79]:
My_API_Key = os.environ.get('CHARGER_KEY')

In [80]:
xmlUrl = 'http://apis.data.go.kr/B552584/EvCharger/getChargerInfo'

queryParams = '?' + urlencode( 
    {
        quote_plus('ServiceKey') : My_API_Key,
        quote_plus('pageNo') : '1',         
        quote_plus('numOfRows') : '9999',
        quote_plus('zcode') : '11'

     }
)

response = requests.get(xmlUrl + queryParams).text.encode('utf-8')
xmlobj = bs4.BeautifulSoup(response, 'html.parser')

In [81]:
from tqdm import tqdm

i = 0

df = pd.DataFrame(columns=['statNm', 'statId', 'chgerld', 'chgerType', 
                           'addr', 'lat', 'lng', 'useTime',
                           'busild','busiNm','busiCall', 'stat',
                           'statUpdDt', 'powerTpye', 'output', 'method',
                           'zcode', 'parkingFree', 'note', 'limitYn',
                           'limitDetail', 'delYn', 'delDetail'])
items = xmlobj.find("items")
for item in tqdm(items.findAll("item")):
    df.loc[i] = [item.statnm.text, item.statid.text, item.chgerid.text, item.chgertype.text,
                 item.addr.text, item.lat.text, item.lng.text, item.usetime.text,
                 item.busiid.text, item.businm.text, item.busicall.text,
                 item.stat.text, item.statupddt.text, item.powertype.text,
                 item.output.text, item.method.text, item.zcode.text,
                 item.parkingfree.text, item.note.text, item.limityn.text,
                 item.limitdetail.text, item.delyn.text, item.deldetail.text]
    i += 1

100%|█████████████████████████████████████████████████████████████████████████████| 9999/9999 [01:34<00:00, 105.36it/s]

In [82]:
df.to_csv('electric_charger.csv')

In [83]:
df.head(10)

,statNm,statId,chgerld,chgerType,addr,lat,lng,useTime,busild,busiNm,...,powerTpye,output,method,zcode,parkingFree,note,limitYn,limitDetail,delYn,delDetail
0,종묘 공영주차장,ME000001,01,03,서울특별시 ...,37.571076,126.99588,24시간 이용가능,ME,환경부,...,,50,단독,11,Y,,N,,N,
1,세종로 공영주차장,ME000002,01,06,서울특별시 ...,37.573611,126.97...,24시간 이용가능,ME,환경부,...,,50,단독,11,Y,,N,,N,
2,그랜드앰배서...,ME000003,01,06,서울특별시 ...,37.559352,127.00...,24시간 이용가능,ME,환경부,...,,50,단독,11,N,,N,,N,
3,한강진역 공...,ME000004,01,03,서울특별시 ...,37.540085,127.00...,24시간 이용가능,ME,환경부,...,,50,단독,11,Y,,N,,N,
4,기아차 성동...,ME000005,01,03,서울특별시 ...,37.544834,127.06...,24시간 이용가능,ME,환경부,...,,50,단독,11,N,201906...,Y,201906...,N,
5,마장동사무소...,ME000006,01,06,서울특별시 ...,37.566...,127.04...,24시간 이용가능,ME,환경부,...,,50,단독,11,N,,N,,N,
6,청량리롯데백화점,ME000007,01,03,서울특별시 ...,37.580650,127.04...,24시간 이용가능,ME,환경부,...,,50,단독,11,N,,N,,N,
7,이마트 이문점,ME000008,01,03,서울특별시 ...,37.598454,127.06...,10:00~...,ME,환경부,...,,50,단독,11,N,,N,,N,
8,홈플러스 면목점,ME000010,01,03,서울특별시 ...,37.580612,127.08154,10:00~...,ME,환경부,...,,50,단독,11,N,,N,,N,
9,홈플러스 월곡점,ME000011,01,03,서울특별시 ...,37.602...,127.04...,10:00~...,ME,환경부,...,,50,단독,11,N,,N,,N,

서울시 전기충전소 **최적화 코드**입니다.

In [84]:
# 최적화 공식

def optimize(region):
    try:
        # Create a new model
        m = gp.Model("milp")

        # Create variables
        for i in range(1, len(region)+1):
            globals()['x%d'%i] = m.addVar(vtype=GRB.INTEGER, name="x%d"%i)
        for i in range(0, len(region)):
            globals()['y%d'%(i+1)] = region.loc[i, '충전소 수']
            globals()['n%d'%(i+1)] = region.loc[i, 'population']
            
        # Standard Value Setting
        p = 1000000/1500
        # Set objective
        obj = None
        for i in range(1, len(region)+1):
            obj += globals()['x%d'%i] * globals()['n%d'%i]
        m.setObjective(obj, GRB.MAXIMIZE)

        const = globals()['x1']
        for i in range(2, len(region)+1):
            const +=  globals()['x%d'%i]

        # Add constraint: x + 2 y + 3 z <= 4
        m.addConstr(1400 * const <= 269000, "c0")

        # Add constraint: x + y >= 1
        for i in range(1, len(region)+1):
            if globals()['n%d'%i]/p - globals()['y%d'%i] > 0:
                m.addConstr(globals()['x%d'%i] <= globals()['n%d'%i]/p - globals()['y%d'%i], "c_%d"%i)
            else:
                m.addConstr(globals()['x%d'%i] <= 0)

        # Optimize model
        m.optimize()

        for v in m.getVars():
            print('%s %g' % (v.varName, v.x))

        print('Obj: %g' % m.objVal)
        
        return m

    except gp.GurobiError as e:
        print('Error code ' + str(e.errno) + ': ' + str(e))
        return None

    except AttributeError:
        print('Encountered an attribute error')
        return None

생활인구 낮 & 밤 가중치 부여 코드입니다.

In [85]:
# Data Load

df = pd.read_csv('EV_2020.csv', encoding='cp949')
df.head()
df = df.groupby('일시').sum().mean()
df_noon = df.iloc[9:18]
df_night = df.drop(index=df_noon.index)

df_noon.mean()
df_night.mean()
Noon = df_noon.mean() /(df_noon.mean() + df_night.mean())
Night = df_night.mean() /(df_noon.mean() + df_night.mean())

# 전기차량 낮/밤 가중치
print((Noon, Night))

(0.6870964134313272, 0.31290358656867273)

서울시 전기 충전소 현황(초기)

In [86]:
# 낮/밤 충전소 부하량

region = pd.read_csv('Region_Charger.csv')
region.rename(columns={'Unnamed: 0':'loc'}, inplace=True)
region.head(10)

    loc       noon      night  충전소 수
0   강동구  260045...  295823...    285
1   송파구  469660...  471872...    540
2   강남구  664934...  465326...    660
3   서초구  450708...  342209...    751
4   관악구  278161...  336942...    254
5   동작구  223512...  257178...    307
6  영등포구  359691...  288125...    421
7   금천구  165505...  139008...    365
8   구로구  245558...  247917...    495
9   강서구  315460...  343064...    609

서울시 구별 생활인구 가중치 합산

In [87]:
# 낮/밤 충전소 + 인구 데이터

region.loc[:,'population'] = region.noon * Noon + region.night * Night
region.loc[:, 'proportion'] = region.population/ region.iloc[:,3]
region = region.drop(columns = ['noon', 'night'], axis = 1)

In [88]:
region.head(10)

    loc  충전소 수  population  proportion
0   강동구    285  271240...   951.72...
1   송파구    540  470352...   871.02...
2   강남구    660  602476...   912.84...
3   서초구    751  416758...   554.93...
4   관악구    254  296554...   1167.5...
5   동작구    307  234046...   762.36...
6  영등포구    421  337297...   801.18...
7   금천구    365  157214...   430.72...
8   구로구    495  246296...   497.56...
9   강서구    609  324097...   532.18...

5개년도 서울시 전기 충전소 확충 최적화 코드입니다.

In [89]:
project_year = 5

for i in range(project_year):
    m = optimize(region)
    if m == None:
        print('최적화 실패')
        break;
    lst = []
    for e in m.getVars() :
        lst.append(e.x)
    if i == 0:
        data = pd.DataFrame(lst, columns = ['Year{}'.format(i)], index = region.iloc[:,0])
    else:
        data = pd.concat([data, pd.DataFrame(lst, columns = ['Year{}'.format(i)], index = region.iloc[:,0])], axis=1)
    region.iloc[:,1] = region.iloc[:,1] + [int(e.x) for e in m.getVars()]

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 26 rows, 25 columns and 50 nonzeros
Model fingerprint: 0x88ecb4c8
Variable types: 0 continuous, 25 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [2e+05, 6e+05]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+01, 3e+05]
Found heuristic solution: objective 6.621519e+07
Presolve removed 26 rows and 25 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 1.15676e+08 6.62152e+07

Optimal solution found (tolerance 1.00e-04)
Best objective 1.156755047354e+08, best bound 1.156755047354e+08, gap 0.0000%
x1 -0
x2 -0
x3 192
x4 0
x5 -0
x6 -0
x7 -0
x8 0
x9 0
x10 0
x11 0
x12 -0
x13 -0
x14 0
x15 -0
x16 0
x17 -0
x18 0
x19 0
x20 0
x21 -0
x22 0
x23 0
x24 -0
x25 -0
Obj: 1.15676e+08
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 26 rows, 25 columns and 50 nonzeros
Model fingerprint: 0x6f86346e
Variable types: 0 continuous, 25 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [2e+05, 6e+05]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+01, 3e+05]
Found heuristic solution: objective 6.621519e+07
Presolve removed 25 rows and 12 columns
Presolve time: 0.00s
Presolved: 1 rows, 13 columns, 13 nonzeros
Variable types: 0 continuous, 13 integer (0 binary)

Root relaxation: objective 9.704601e+07, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0    9.704601e+07 9.7046e+07  0.00%     -    0s

Explored 0 nodes (1 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 9.7046e+07 6.62152e+07

Optimal solution found (tolerance 1.00e-04)
Best objective 9.704601217625e+07, best bound 9.704601217625e+07, gap 0.0000%
x1 -0
x2 141
x3 51
x4 0
x5 -0
x6 -0
x7 -0
x8 0
x9 0
x10 0
x11 0
x12 -0
x13 -0
x14 0
x15 -0
x16 0
x17 -0
x18 0
x19 0
x20 0
x21 -0
x22 0
x23 0
x24 -0
x25 -0
Obj: 9.7046e+07
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 26 rows, 25 columns and 50 nonzeros
Model fingerprint: 0x2b25a697
Variable types: 0 continuous, 25 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [2e+05, 6e+05]
  Bounds range     [0e+00, 0e+00]
  RHS range        [7e-01, 3e+05]
Found heuristic solution: objective 5.804666e+07
Presolve removed 25 rows and 13 columns
Presolve time: 0.00s
Presolved: 1 rows, 12 columns, 12 nonzeros
Variable types: 0 continuous, 12 integer (0 binary)

Root relaxation: objective 6.486325e+07, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0    6.486325e+07 6.4863e+07  0.00%     -    0s

Explored 0 nodes (1 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 6.48632e+07 5.80467e+07

Optimal solution found (tolerance 1.00e-04)
Best objective 6.486324906489e+07, best bound 6.486324906489e+07, gap 0.0000%
x1 -0
x2 24
x3 0
x4 0
x5 64
x6 -0
x7 84
x8 0
x9 0
x10 0
x11 0
x12 20
x13 -0
x14 0
x15 -0
x16 0
x17 -0
x18 0
x19 0
x20 0
x21 -0
x22 0
x23 0
x24 -0
x25 -0
Obj: 6.48632e+07
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 26 rows, 25 columns and 50 nonzeros
Model fingerprint: 0xbd8641e6
Variable types: 0 continuous, 25 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [2e+05, 6e+05]
  Bounds range     [0e+00, 0e+00]
  RHS range        [5e-01, 3e+05]
Found heuristic solution: objective 5.387550e+07
Presolve removed 26 rows and 25 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 5.53199e+07 5.38755e+07

Optimal solution found (tolerance 1.00e-04)
Best objective 5.531993729367e+07, best bound 5.531993729367e+07, gap 0.0000%
x1 57
x2 0
x3 0
x4 0
x5 126
x6 0
x7 0
x8 0
x9 0
x10 0
x11 0
x12 0
x13 0
x14 0
x15 9
x16 0
x17 0
x18 0
x19 0
x20 0
x21 0
x22 0
x23 0
x24 0
x25 0
Obj: 5.53199e+07
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 26 rows, 25 columns and 50 nonzeros
Model fingerprint: 0x87d3b8b2
Variable types: 0 continuous, 25 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [2e+05, 6e+05]
  Bounds range     [0e+00, 0e+00]
  RHS range        [5e-01, 3e+05]
Found heuristic solution: objective 4.643056e+07
Presolve removed 26 rows and 25 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 4.87598e+07 4.64306e+07

Optimal solution found (tolerance 1.00e-04)
Best objective 4.875980081238e+07, best bound 4.875980081238e+07, gap 0.0000%
x1 64
x2 0
x3 0
x4 0
x5 0
x6 44
x7 0
x8 0
x9 0
x10 0
x11 0
x12 0
x13 0
x14 0
x15 0
x16 0
x17 0
x18 0
x19 0
x20 0
x21 0
x22 0
x23 0
x24 84
x25 0
Obj: 4.87598e+07

각 년도별 확충될 전기 충전소 수

In [90]:
data.T

loc,강동구,송파구,강남구,서초구,관악구,동작구,영등포구,금천구,구로구,강서구,...,도봉구,강북구,성북구,중랑구,동대문구,광진구,성동구,용산구,중구,종로구
Year0,-0.0,-0.0,192.0,0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,...,0.0,-0.0,0.0,0.0,0.0,-0.0,0.0,0.0,-0.0,-0.0
Year1,-0.0,141.0,51.0,0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,...,0.0,-0.0,0.0,0.0,0.0,-0.0,0.0,0.0,-0.0,-0.0
Year2,-0.0,24.0,0.0,0.0,64.0,-0.0,84.0,0.0,0.0,0.0,...,0.0,-0.0,0.0,0.0,0.0,-0.0,0.0,0.0,-0.0,-0.0
Year3,57.0,0.0,0.0,0.0,126.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Year4,64.0,0.0,0.0,0.0,0.0,44.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,0.0

In [91]:
data.to_csv('Add.csv')

### Mapping
서울시 행정구별 생활인구 세부 데이터

In [92]:
df = pd.read_csv('LOCAL_PEOPLE_GU_2019.csv', encoding='cp949',index_col = False)
df.head(10)

,기준일ID,시간대구분,자치구코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20190101,0,11110,247783...,6613.1044,3564.9470,6134.7190,12757....,13424....,9679.4043,...,11592....,8455.5240,8669.4651,7764.7926,9659.7779,8421.0455,8671.2045,8079.0106,6242.6970,17962....
1,20190101,0,11140,176516...,4735.9065,1857.9963,3251.4707,7456.5552,8482.9745,8253.8513,...,8654.7543,7425.3943,7345.0904,5858.8981,6255.6065,5525.2377,6293.4810,5906.2118,4298.7062,12303....
2,20190101,0,11170,287806...,7274.7405,3654.3768,5865.4531,11656....,15548....,14457....,...,16203....,13423....,13009....,10794....,10880....,8360.3558,9568.1641,8703.7465,6648.3724,20296....
3,20190101,0,11200,335106...,12278....,5306.1528,6766.7787,11593....,13941....,13447....,...,13656....,14046....,15142....,12029....,13051....,11475....,13219....,12022....,9093.4057,24370....
4,20190101,0,11215,399818...,12003....,6472.3827,12056....,17503....,18611....,16219....,...,17737....,16189....,16158....,14059....,15750....,14705....,15708....,14021....,9907.6266,24975....
5,20190101,0,11230,362330...,11537....,5769.9767,7622.3130,14716....,15126....,12870....,...,14091....,13018....,14144....,11924....,13261....,12273....,14141....,13551....,9997.5845,31248....
6,20190101,0,11260,390331...,13572....,6606.2092,8534.7441,11428....,13307....,13611....,...,13369....,13777....,15620....,13202....,15933....,15687....,18402....,15598....,11508....,31154....
7,20190101,0,11290,454896...,17367....,9739.8882,11294....,15681....,15990....,13319....,...,15337....,14572....,17686....,17086....,18926....,16343....,17844....,16773....,12671....,38060....
8,20190101,0,11305,326993...,10362....,5680.6360,7520.6531,10990....,11034....,10469....,...,10691....,9615.5839,11335....,11468....,13644....,12670....,14479....,13047....,11104....,30846....
9,20190101,0,11320,316057...,10973....,6115.0086,7217.4849,8714.6292,9449.7792,9571.7749,...,9606.4405,9503.0264,11804....,10770....,13762....,12814....,14905....,13885....,9950.6149,28954....

생활인구 나이대별 전기차 가용인구 합계

In [93]:
male = df.iloc[:,7:15]
female = df.iloc[:,22:30]

df['sum'] = 0

for e in set(male.columns)|set(female.columns):
    df['sum'] += df[e]
    
c = pd.concat([df.iloc[:,0:3], df['sum']], axis=1)
df = c.groupby(['자치구코드', '시간대구분']).mean().reset_index().drop(columns=['기준일ID'])

for e in set(df['자치구코드']):
    idx = df[df['자치구코드']==e].index
    if e == 11110:
        df.loc[idx, '자치구코드'] = '종로구'
    elif e == 11140:
        df.loc[idx, '자치구코드'] = '중구'
    elif e == 11170:
        df.loc[idx, '자치구코드'] = '용산구'
    elif e == 11200:
        df.loc[idx, '자치구코드'] = '성동구'
    elif e == 11215:
        df.loc[idx, '자치구코드'] = '광진구'
    elif e == 11230:
        df.loc[idx, '자치구코드'] = '동대문구'
    elif e == 11260:
        df.loc[idx, '자치구코드'] = '중랑구'
    elif e == 11290:
        df.loc[idx, '자치구코드'] = '성북구'
    elif e == 11305:
        df.loc[idx, '자치구코드'] = '강북구'
    elif e == 11320:
        df.loc[idx, '자치구코드'] = '도봉구'
    elif e == 11350:
        df.loc[idx, '자치구코드'] = '노원구'
    elif e == 11380:
        df.loc[idx, '자치구코드'] = '은평구'
    elif e == 11410:
        df.loc[idx, '자치구코드'] = '서대문구'
    elif e == 11440:
        df.loc[idx, '자치구코드'] = '마포구'
    elif e == 11470:
        df.loc[idx, '자치구코드'] = '양천구'
    elif e == 11500:
        df.loc[idx, '자치구코드'] = '강서구'
    elif e == 11530:
        df.loc[idx, '자치구코드'] = '구로구'
    elif e == 11545:
        df.loc[idx, '자치구코드'] = '금천구'
    elif e == 11560:
        df.loc[idx, '자치구코드'] = '영등포구'
    elif e == 11590:
        df.loc[idx, '자치구코드'] = '동작구'
    elif e == 11620:
        df.loc[idx, '자치구코드'] = '관악구'
    elif e == 11650:
        df.loc[idx, '자치구코드'] = '서초구'
    elif e == 11680:
        df.loc[idx, '자치구코드'] = '강남구'
    elif e == 11710:
        df.loc[idx, '자치구코드'] = '송파구'
    elif e == 11740:
        df.loc[idx, '자치구코드'] = '강동구'

json 파일에 시간대별 가중치 적용

In [94]:
df = df.set_index(['자치구코드', '시간대구분']).unstack()

a = df.iloc[:,9:18]
b = df.drop(columns=df.iloc[:,9:18].columns)

df['noon'] = 0
df['night'] = 0

for e in a.columns:
    df['noon'] += df[e]
    df.drop(columns=[e], inplace=True)
for e in b.columns:
    df['night'] += df[e]
    df.drop(columns=[e], inplace=True)
df['noon'] = df['noon']/9
df['night'] = df['night']/15
df.reset_index(inplace=True)

geo_json = 'https://raw.githubusercontent.com/southkorea/seoul-maps/master/kostat/2013/json/seoul_municipalities_geo_simple.json'
json_data = json.loads(requests.get(geo_json).text)

In [95]:
for e in json_data['features']:
    e['geometry']['coordinates'] = [list(map(lambda x : [x[0]-0.00250000000000, x[1] + 0.00250000000000], e['geometry']['coordinates'][0]))]

json 파일과 위치정보를 담고 있는 geojason 파일 연동

In [96]:
d = pd.read_csv('electric_charger.csv')
d=d.fillna('')
df2=d[['statNm', 'addr','lat','lng']]
df2=df2.rename(columns={'lat':'lat','lng':'lon'})
df2=df2[df2['lat']!='']
df2=df2[df2['lon']!='']
df2['lat']=df2['lat'].astype(float)
df2['lon']=df2['lon'].astype(float)

geo_data = df_to_geojson(
    df=df2,
    properties=['statNm', 'addr'],
    lat='lat', lon='lon',
    precision=5,
    filename = "parks.geojson"
)
geo_data_2 = 'parks.geojson'

with open(geo_data_2) as f:
    data = json.loads(f.read())

lst = []
dict_ = {}

for e in data['features']:
    try:
        if e['properties']['addr'].split(' ')[1] == '입구좌측,':
            e['properties']['gu'] = '관악구'
        else:
            e['properties']['gu'] = e['properties']['addr'].split(' ')[1]
            lst.append(e['properties']['gu'])
    except:
        e['properties']['gu'] = '금천구'
        lst.append('금천구')
lst = set(lst)

for e in lst:
    dict_[e] = 0
    
for e in data['features']:
    dict_[e['properties']['gu']] += 1

C:\Users\USER\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

json 파일에 낮/밤 시간대별 [생활인구/전기 충전소] 비율을 추가해주는 함수입니다.

In [97]:
def percentile_cal(json_data):
    max_noon = 0
    min_noon = sys.maxsize
    max_night = 0
    min_night = sys.maxsize
    
    for e in json_data['features']:
        for e2 in list(dict_.keys()):
            if e['properties']['name'] == e2:
                #e['properties']['stations'] = dict_[e2]
                e['properties']['noon_percentile'] = e['properties']['noon']/e['properties']['stations']
                e['properties']['night_percentile'] = e['properties']['night']/e['properties']['stations']
                if e['properties']['noon_percentile'] > max_noon :
                    max_noon = e['properties']['noon_percentile']
                if e['properties']['noon_percentile'] < min_noon:
                    min_noon = e['properties']['noon_percentile']
                if e['properties']['night_percentile'] > max_night :
                    max_night = e['properties']['night_percentile']
                if e['properties']['night_percentile'] < min_night:
                    min_night = e['properties']['night_percentile']
    return json_data

In [100]:
for e in json_data['features']:
    for e2 in df['자치구코드']:
        if e['properties']['name'] == e2:
            e['properties']['noon'] = df[df['자치구코드'] == e2]['noon'].iloc[0]
            e['properties']['night'] = df[df['자치구코드'] == e2]['night'].iloc[0]

max_noon = 0
min_noon = sys.maxsize
max_night = 0
min_night = sys.maxsize

for e in json_data['features']:
    for e2 in list(dict_.keys()):
        if e['properties']['name'] == e2:
            e['properties']['stations'] = dict_[e2]
            e['properties']['noon_percentile'] = e['properties']['noon']/e['properties']['stations']
            e['properties']['night_percentile'] = e['properties']['night']/e['properties']['stations']
            if e['properties']['noon_percentile'] > max_noon :
                max_noon = e['properties']['noon_percentile']
            if e['properties']['noon_percentile'] < min_noon:
                min_noon = e['properties']['noon_percentile']
            if e['properties']['night_percentile'] > max_night :
                max_night = e['properties']['night_percentile']
            if e['properties']['night_percentile'] < min_night:
                min_night = e['properties']['night_percentile']

각 행정구별 주요 정보를 데이터 프레임으로 정리하는 함수입니다.

In [101]:
def make_data(json_data):
    df = pd.DataFrame([])
    idx = 0
    for e in json_data['features']:
        
        df.loc[idx, 'name'] = e['properties']['name']
        df.loc[idx, 'name_eng'] = e['properties']['name_eng']
        df.loc[idx, 'noon'] = e['properties']['noon']
        df.loc[idx, 'night'] = e['properties']['night']
        df.loc[idx, 'stations'] = e['properties']['stations']
        df.loc[idx, 'noon_percentile'] = e['properties']['noon_percentile']
        df.loc[idx, 'night_percentile'] = e['properties']['night_percentile']
        try:
            df.loc[idx, 'install'] = e['properties']['install']
        except:
            pass
        idx += 1

    return df

json 파일에 당해년도에 설치할 충전소의 수를 추가하는 함수입니다.

In [102]:
def install(year, data, json_data):
    for e1 in json_data['features']:
        for e2 in data[year]:
            if e1['properties']['name'] == e2:
                e1['properties']['install'] = data[year][e2]
                e1['properties']['stations'] += data[year][e2]
    return json_data

각 연도별 설치해야할 충전소의 위치와 개수에 대한 최적화 결과를 나타냅니다.

In [103]:
df = pd.read_csv("Add.csv").set_index('loc')
df.to_json("practice.json",orient='columns')

geo_data_2 = 'practice.json'

with open(geo_data_2) as f:
    data = json.loads(f.read())

5개년도 전기 충전소 확충 프로젝트에 대한 시각화 결과입니다.

In [104]:
color_breaks = [300, 600, 900, 1200, 1500]
TOKEN = os.environ.get('TOKEN')
token = TOKEN
color_stops = create_color_stops(color_breaks, colors='YlGn')
viz_noon_0 = ChoroplethViz(
    data = json_data,
    access_token = token,
    color_property = 'noon_percentile',
    color_stops = color_stops,
    center = [126.986, 37.565],
    zoom=10
)

color_stops = create_color_stops(color_breaks, colors='BuPu')
viz_night_0 = ChoroplethViz(
    data = json_data,
    access_token = token,
    color_property = 'night_percentile',
    color_stops = color_stops,
    center = [126.986, 37.565],
    zoom=10
)

viz_noon_0.create_html("./viz_noon_0.html")

viz_night_0.create_html("./viz_night_0.html")


for i in range(0, 5):
    json_data = install('Year{}'.format(i), data, json_data)
    json_data = percentile_cal(json_data)
    
    color_stops = create_color_stops(color_breaks, colors='YlGn')
    globals()["viz_noon_{}".format(i)] = ChoroplethViz(
        data = json_data,
        access_token = token,
        color_property = 'noon_percentile',
        color_stops = color_stops,
        center = [126.986, 37.565],
        zoom=10
    )

    color_stops = create_color_stops(color_breaks, colors='BuPu')
    globals()["viz_night_{}".format(i)] = ChoroplethViz(
        data = json_data,
        access_token = token,
        color_property = 'night_percentile',
        color_stops = color_stops,
        center = [126.986, 37.565],
        zoom=10
    )

    globals()["viz_noon_{}".format(i)].create_html("./viz_noon_{}.html".format(i+1))

    globals()["viz_night_{}".format(i)].create_html("./viz_night_{}.html".format(i+1))
    
    
    df_0 = make_data(json_data)
    df_0.to_csv('./Year{}.csv'.format(i), encoding='cp949')

### 2-3. Visualization(PyeChart)

고속도로별 연간 통행량

In [105]:
highway = pd.read_csv('highway.csv')
highway = highway.sort_values(by = ['year'], ascending = False)
name = highway['name'].tolist()
year = np.array(highway['year'].tolist())
day = np.array(highway['day'].tolist())

bar = Bar('고속도로별 연간 통행량(2019)',width=900, height=540)
bar.use_theme('macarons')
bar.add(name= '연간 통행량',x_axis=name, y_axis=year, yaxis_max=500000000, is_legend_show=False, is_label_show=True,
        is_datazoom_show=True, datazoom_type = 'slider', datazoom_range = [0,7], yaxis_rotate = 45)
bar.render('고속도로별 연간 통행량.html')

고속도로별 교통량별 구간 수

In [106]:
top3 = pd.read_excel('Top_solve.xlsx')

seoul = top3.iloc[0:54,:]
sb = top3.iloc[54:87,:]
yd = top3.iloc[87:,:]

seoul = seoul.reset_index(drop = True)
sb = sb.reset_index(drop = True)
yd = yd.reset_index(drop = True)

seoul['label'] = ""

for i in range(len(seoul)):
    if seoul.iloc[i,3]>=100000 and seoul.iloc[i,3] < 120000:
        seoul.loc[i,'label'] = '10만 이상 12만 미만'
    elif seoul.iloc[i,3] >= 120000 and seoul.iloc[i,3] < 140000:
        seoul.loc[i,'label'] = '12만 이상 14만 미만'
    elif seoul.iloc[i,3] >= 140000 and seoul.iloc[i,3] < 160000:
        seoul.loc[i,'label'] = '14만 이상 16만 미만'
    elif seoul.iloc[i,3] >= 160000 and seoul.iloc[i,3] < 180000:
        seoul.loc[i,'label'] = '16만 이상 18만 미만'
    elif seoul.iloc[i,3] >= 180000 and seoul.iloc[i,3] < 200000:
        seoul.loc[i,'label'] = '18만 이상 20만 미만'
    elif seoul.iloc[i,3] >= 200000:
        seoul.loc[i,'label'] = '20만 이상'
    else:
        seoul.loc[i,'label'] = '10만 미만'

sb['label'] = ""

for i in range(len(sb)):
    if sb.iloc[i,3]>=100000 and sb.iloc[i,3] < 120000:
        sb.loc[i,'label'] = '10만 이상 12만 미만'
    elif sb.iloc[i,3] >= 120000 and sb.iloc[i,3] < 140000:
        sb.loc[i,'label'] = '12만 이상 14만 미만'
    elif sb.iloc[i,3] >= 140000 and sb.iloc[i,3] < 160000:
        sb.loc[i,'label'] = '14만 이상 16만 미만'
    elif sb.iloc[i,3] >= 160000 and sb.iloc[i,3] < 180000:
        sb.loc[i,'label'] = '16만 이상 18만 미만'
    elif sb.iloc[i,3] >= 180000 and sb.iloc[i,3] < 200000:
        sb.loc[i,'label'] = '18만 이상 20만 미만'
    elif sb.iloc[i,3] >= 200000:
        sb.loc[i,'label'] = '20만 이상'
    else:
        sb.loc[i,'label'] = '10만 미만'

yd['label'] = ""

for i in range(len(yd)):
    if yd.iloc[i,3]>=100000 and yd.iloc[i,3] < 120000:
        yd.loc[i,'label'] = '10만 이상 12만 미만'
    elif yd.iloc[i,3] >= 120000 and yd.iloc[i,3] < 140000:
        yd.loc[i,'label'] = '12만 이상 14만 미만'
    elif yd.iloc[i,3] >= 140000 and yd.iloc[i,3] < 160000:
        yd.loc[i,'label'] = '14만 이상 16만 미만'
    elif yd.iloc[i,3] >= 160000 and yd.iloc[i,3] < 180000:
        yd.loc[i,'label'] = '16만 이상 18만 미만'
    elif yd.iloc[i,3] >= 180000 and yd.iloc[i,3] < 200000:
        yd.loc[i,'label'] = '18만 이상 20만 미만'
    elif yd.iloc[i,3] >= 200000:
        yd.loc[i,'label'] = '20만 이상'
    else:
        yd.loc[i,'label'] = '10만 미만'

seoul_pie = seoul.groupby(seoul['label']).size()
seoul_pie = pd.DataFrame(seoul_pie)
seoul_pie = seoul_pie.reset_index()

sb_pie = sb.groupby(sb['label']).size()
sb_pie = pd.DataFrame(sb_pie)
sb_pie = sb_pie.reset_index()

yd_pie = yd.groupby(yd['label']).size()
yd_pie = pd.DataFrame(yd_pie)
yd_pie = yd_pie.reset_index()

attr = seoul_pie['label'].tolist()
v1 = seoul_pie[0].tolist()

attr_2 = sb_pie['label'].tolist()
attr_2.insert(0,'10만 이상 12만 미만')
attr_2.insert(0,'10만 미만')
v2 = sb_pie[0].tolist()
v2.insert(0, 0)
v2.insert(0, 0)

attr_3 = yd_pie['label'].tolist()
attr_3.extend(['18만 이상 20만 미만', '20만 이상'])
v3 = yd_pie[0].tolist()
v3.extend([0,0])

style = Style()
pie_style = style.add(
    label_pos = 'center',
    is_label_show = True,
    label_text_color = None,
    legend_top = 'bottom'
)

pie_1 = Pie("교통량별 구간 수 : 서울외곽선", width=280, height=180, title_pos = '33%')
pie_1.use_theme('macarons')
pie_1.add("서울외곽선", attr, v1, legend_pos = 'center', legend_orient = 'horizontal', radius = [50, 70], center = [50,50], **pie_style)
pie_1.render('Top3_Seoul.html')

pie_2 = Pie("교통량별 구간 수 : 경부선", width=280, height=180)
pie_2.use_theme('macarons')
pie_2.add("경부선", attr_2, v2, legend_pos = 'center', legend_orient = 'horizontal', radius = [50,70], center = [20,50], **pie_style)
pie_2.render('Top3_sb.html')

pie_3 = Pie("교통량별 구간 수 : 영동선", width=280, height=180, title_pos = '66%')
pie_3.use_theme('macarons')
pie_3.add("영동선", attr_3, v3, legend_pos = 'center', legend_orient = 'horizontal', radius = [50,70], center = [80,50], **pie_style)
pie_3.render('Top3_yd.html')

grid = Grid('교통량별 구간 수', width = 900, height = 360)
grid.add(pie_2, grid_left='0%')
grid.add(pie_1, grid_left='33%')
grid.add(pie_3, grid_left='66%')
grid.render('Top3.html')

5개년도 진행상황(무선 충전도로)

In [107]:
progress = pd.read_excel('progress.xlsx')

sb = progress.iloc[0:54,:]
seoul = progress.iloc[54:87,:]
yd = progress.iloc[87:,:]

seoul = seoul.reset_index(drop = True)
sb = sb.reset_index(drop = True)
yd = yd.reset_index(drop = True)

#seoul
seoul_1 = seoul[['구간','1개년']]
seoul_1_count = seoul_1.groupby(seoul_1['1개년']).size()
seoul_1_count = seoul_1_count.reset_index()

status_1 = ['Carry Forward','Complete','None','Progressing']
v_1 = seoul_1_count[0].tolist()
v_1.insert(1,0)

seoul_2 = seoul[['구간','2개년']]
seoul_2_count = seoul_2.groupby(seoul_2['2개년']).size()
seoul_2_count = seoul_2_count.reset_index()

status_2 = ['Carry Forward','Complete','None','Progressing']
v_2 = seoul_2_count[0].tolist()


seoul_3 = seoul[['구간','3개년']]
seoul_3_count = seoul_3.groupby(seoul_3['3개년']).size()
seoul_3_count = seoul_3_count.reset_index()

status_3 = ['Carry Forward','Complete','None','Progressing']
v_3 = seoul_3_count[0].tolist()
v_3.insert(0,0)

seoul_4 = seoul[['구간','4개년']]
seoul_4_count = seoul_4.groupby(seoul_4['4개년']).size()
seoul_4_count = seoul_4_count.reset_index()

status_4 = ['Carry Forward','Complete','None','Progressing']
v_4 = seoul_4_count[0].tolist()


seoul_5 = seoul[['구간','5개년']]
seoul_5_count = seoul_5.groupby(seoul_5['5개년']).size()
seoul_5_count = seoul_5_count.reset_index()

status_5 = ['Carry Forward','Complete','None','Progressing']
v_5 = seoul_5_count[0].tolist()


pie_seoul_1 = Pie("서울외곽선",'진행상황', width=200, height=180, title_pos="33%")
pie_seoul_1.use_theme('macarons')
style = Style()
pie_style = style.add(
    label_pos = 'center',
    is_label_show = True,
    label_text_color = None,
    legend_pos = 'right',
    legend_orient = 'vertical',
)
pie_seoul_1.add("1개년",status_1,v_1, is_random = False, radius = [35, 60], center = [50,50], **pie_style)

pie_seoul_2 = Pie("서울외곽선",'진행상황', width=200, height=180, title_pos="33%")
pie_seoul_2.use_theme('macarons')
pie_seoul_2.add("2개년",status_2,v_2, is_random = False, radius = [35, 60], center = [50,50], **pie_style)

pie_seoul_3 = Pie("서울외곽선",'진행상황', width=200, height=180, title_pos="33%")
pie_seoul_3.use_theme('macarons')
pie_seoul_3.add("3개년",status_3,v_3, is_random = False, radius = [35, 60], center = [50,50], **pie_style)

pie_seoul_4 = Pie("서울외곽선",'진행상황', width=200, height=180, title_pos="33%")
pie_seoul_4.use_theme('macarons')
pie_seoul_4.add("4개년",status_4,v_4, is_random = False, radius = [35, 60], center = [50,50], **pie_style)

pie_seoul_5 = Pie("서울외곽선",'진행상황', width=200, height=180, title_pos="33%")
pie_seoul_5.use_theme('macarons')
pie_seoul_5.add("5개년",status_5,v_5, is_random = False, radius = [35, 60], center = [50,50], **pie_style)

#sb
sb_1 = sb[['구간','1개년']]
sb_1_count = sb_1.groupby(sb_1['1개년']).size()
sb_1_count = sb_1_count.reset_index()

status_1 = ['Carry Forward','Complete','None','Progressing']
v_1 = sb_1_count[0].tolist()
v_1.insert(0,0)
v_1.insert(0,0)

sb_2 = sb[['구간','2개년']]
sb_2_count = sb_2.groupby(sb_2['2개년']).size()
sb_2_count = sb_2_count.reset_index()

status_2 = ['Carry Forward','Complete','None','Progressing']
v_2 = sb_2_count[0].tolist()
v_2.insert(0,0)

sb_3 = sb[['구간','3개년']]
sb_3_count = sb_3.groupby(sb_3['3개년']).size()
sb_3_count = sb_3_count.reset_index()

status_3 = ['Carry Forward','Complete','None','Progressing']
v_3 = sb_3_count[0].tolist()

sb_4 = sb[['구간','4개년']]
sb_4_count = sb_4.groupby(sb_4['4개년']).size()
sb_4_count = sb_4_count.reset_index()

status_4 = ['Carry Forward','Complete','None','Progressing']
v_4 = sb_4_count[0].tolist()
v_4.insert(0,0)

sb_5 = sb[['구간','5개년']]
sb_5_count = sb_5.groupby(sb_5['5개년']).size()
sb_5_count = sb_5_count.reset_index()

status_5 = ['Carry Forward','Complete','None','Progressing']
v_5 = sb_5_count[0].tolist()
v_5.insert(0,0)

pie_sb_1 = Pie("경부선","진행상황", width=200, height=180)
pie_sb_1.use_theme('macarons')
style = Style()
pie_style = style.add(
    label_pos = 'center',
    is_label_show = True,
    label_text_color = None,
    legend_pos = 'right',
    legend_orient = 'vertical',
)
pie_sb_1.add("1개년",status_1,v_1, is_random = False, radius = [35, 60], center = [20,50], **pie_style)

pie_sb_2 = Pie("경부선","진행상황", width=200, height=180)
pie_sb_2.use_theme('macarons')
pie_sb_2.add("2개년",status_2,v_2, is_random = False, radius = [35, 60], center = [20,50], **pie_style)

pie_sb_3 = Pie("경부선","진행상황", width=200, height=180)
pie_sb_3.use_theme('macarons')
pie_sb_3.add("3개년",status_3,v_3, is_random = False, radius = [35, 60], center = [20,50], **pie_style)

pie_sb_4 = Pie("경부선","진행상황", width=200, height=180)
pie_sb_4.use_theme('macarons')
pie_sb_4.add("4개년",status_4,v_4, is_random = False, radius = [35, 60], center = [20,50], **pie_style)

pie_sb_5 = Pie("경부선","진행상황", width=200, height=180)
pie_sb_5.use_theme('macarons')
pie_sb_5.add("5개년",status_5,v_5, is_random = False, radius = [35, 60], center = [20,50], **pie_style)


#yd
yd_1 = yd[['구간','1개년']]
yd_1_count = yd_1.groupby(yd_1['1개년']).size()
yd_1_count = yd_1_count.reset_index()

status_1 = ['Carry Forward','Complete','None','Progressing']
v_1 = yd_1_count[0].tolist()
v_1.insert(0,0)
v_1.insert(0,0)

yd_2 = yd[['구간','2개년']]
yd_2_count = yd_2.groupby(yd_2['2개년']).size()
yd_2_count = yd_2_count.reset_index()

status_2 = ['Carry Forward','Complete','None','Progressing']
v_2 = yd_2_count[0].tolist()
v_2.insert(0,0)

yd_3 = yd[['구간','3개년']]
yd_3_count = yd_3.groupby(yd_3['3개년']).size()
yd_3_count = yd_3_count.reset_index()

status_3 = ['Carry Forward','Complete','None','Progressing']
v_3 = yd_3_count[0].tolist()
v_3.insert(0,0)

yd_4 = yd[['구간','4개년']]
yd_4_count = yd_4.groupby(yd_4['4개년']).size()
yd_4_count = yd_4_count.reset_index()

status_4 = ['Carry Forward','Complete','None','Progressing']
v_4 = yd_4_count[0].tolist()
v_4.insert(0,0)
v_4.insert(3,0)

yd_5 = yd[['구간','5개년']]
yd_5_count = yd_5.groupby(yd_5['5개년']).size()
yd_5_count = yd_5_count.reset_index()

status_5 = ['Carry Forward','Complete','None','Progressing']
v_5 = yd_5_count[0].tolist()
v_5.insert(0,0)

pie_yd_1 = Pie("영동선",'진행상황', width=200, height=180, title_pos = '66%')
pie_yd_1.use_theme('macarons')
style = Style()
pie_style = style.add(
    label_pos = 'center',
    is_label_show = True,
    label_text_color = None,
    legend_pos = 'right',
    legend_orient = 'vertical'
)
pie_yd_1.add("1개년",status_1,v_1, is_random = False, radius = [35, 60], center = [80,50], **pie_style)

pie_yd_2 = Pie("영동선",'진행상황', width=200, height=180, title_pos = '66%')
pie_yd_2.use_theme('macarons')
pie_yd_2.add("2개년",status_2,v_2, is_random = False, radius = [35, 60], center = [80,50], **pie_style)

pie_yd_3 = Pie("영동선",'진행상황', width=200, height=180, title_pos = '66%')
pie_yd_3.use_theme('macarons')
pie_yd_3.add("3개년",status_3,v_3, is_random = False, radius = [35, 60], center = [80,50], **pie_style)

pie_yd_4 = Pie("영동선",'진행상황', width=200, height=180, title_pos = '66%')
pie_yd_4.use_theme('macarons')
pie_yd_4.add("4개년",status_4,v_4, is_random = False, radius = [35, 60], center = [80,50], **pie_style)

pie_yd_5 = Pie("영동선",'진행상황', width=200, height=180, title_pos = '66%')
pie_yd_5.use_theme('macarons')
pie_yd_5.add("5개년",status_5,v_5, is_random = False, radius = [35, 60], center = [80,50], **pie_style)

grid_1=Grid('진행상황 : 1년차', width = 720)
grid_1.add(pie_sb_1, grid_left = '0%')
grid_1.add(pie_seoul_1, grid_left = '33%')
grid_1.add(pie_yd_1, grid_right = '66%')

grid_2=Grid('진행상황 : 2년차', width = 720)
grid_2.add(pie_sb_2, grid_left = '0%')
grid_2.add(pie_seoul_2, grid_left = '33%')
grid_2.add(pie_yd_2, grid_right = '66%')

grid_3=Grid('진행상황 : 3년차', width = 720)
grid_3.add(pie_sb_3, grid_left = '0%')
grid_3.add(pie_seoul_3, grid_left = '33%')
grid_3.add(pie_yd_3, grid_right = '66%')

grid_4=Grid('진행상황 : 4년차', width = 720)
grid_4.add(pie_sb_4, grid_left = '0%')
grid_4.add(pie_seoul_4, grid_left = '33%')
grid_4.add(pie_yd_4, grid_right = '66%')

grid_5=Grid('진행상황 : 5년차', width = 720)
grid_5.add(pie_sb_5, grid_left = '0%')
grid_5.add(pie_seoul_5, grid_left = '33%')
grid_5.add(pie_yd_5, grid_right = '66%')

timeline_total = Timeline(is_auto_play = True, timeline_bottom=0, width=900)
timeline_total.add(grid_1, '1개년')
timeline_total.add(grid_2, '2개년')
timeline_total.add(grid_3, '3개년')
timeline_total.add(grid_4, '4개년')
timeline_total.add(grid_5, '5개년')
timeline_total.render('진행상황.html')

지역별 충전소 설치 현황

In [108]:
final = pd.read_csv('Year5.csv', encoding = 'cp949')
final = final.sort_values(by = ['stations'], ascending = False)
region = final['name'].to_list()
stations = final['stations'].to_list()

bar_installation = Bar("지역별 충전소 설치 현황","최종", width=900)
bar_installation.use_theme('macarons')
bar_installation.add("지역별 최종 설치 충전소 수",region, stations, is_legend_show=False, is_label_show=True, is_datazoom_show=True, datazoom_type = 'slider', datazoom_range = [0,25], yaxis_max=1000)
bar_installation.render('지역별 충전소 설치 현황.html')

충전소 한대당 감당 인구 수

In [109]:
year_0 = pd.read_csv("Year0.csv", encoding='cp949')
year_1 = pd.read_csv("Year1.csv", encoding='cp949')
year_2 = pd.read_csv("Year2.csv", encoding='cp949')
year_3 = pd.read_csv("Year3.csv", encoding='cp949')
year_4 = pd.read_csv("Year4.csv", encoding='cp949')
year_5 = pd.read_csv("Year5.csv", encoding='cp949')

region = year_0['name']

noon_0 = year_0['noon_percentile']
night_0 = year_0['night_percentile']
noon_1 = year_1['noon_percentile']
night_1 = year_1['night_percentile']
noon_2 = year_2['noon_percentile']
night_2 = year_2['night_percentile']
noon_3 = year_3['noon_percentile']
night_3 = year_3['night_percentile']
noon_4 = year_4['noon_percentile']
night_4 = year_4['night_percentile']
noon_5 = year_5['noon_percentile']
night_5 = year_5['night_percentile']

bar_0 = Bar("충전소 한 대당 감당 인구수", '초기', width = 2000)
bar_0.use_theme('macarons')
bar_0.add("noon", region, noon_0, yaxis_max=1500, xaxis_rotate = -45)
bar_0.add("night", region, night_0, yaxis_max=1500, xaxis_rotate = -45)

bar_1 = Bar("충전소 한 대당 감당 인구수", '1년차', width = 2000)
bar_1.use_theme('macarons')
bar_1.add("noon", region, noon_1, yaxis_max=1500, xaxis_rotate = -45)
bar_1.add("night", region, night_1, yaxis_max=1500, xaxis_rotate = -45)

bar_2 = Bar("충전소 한 대당 감당 인구수", '2년차', width = 2000)
bar_2.use_theme('macarons')
bar_2.add("noon", region, noon_2, yaxis_max=1500, xaxis_rotate = -45)
bar_2.add("night", region, night_2, yaxis_max=1500, xaxis_rotate = -45)

bar_3 = Bar("충전소 한 대당 감당 인구수", '3년차', width = 2000)
bar_3.use_theme('macarons')
bar_3.add("noon", region, noon_3, yaxis_max=1500, xaxis_rotate = -45)
bar_3.add("night", region, night_3, yaxis_max=1500, xaxis_rotate = -45)

bar_4 = Bar("충전소 한 대당 감당 인구수", '4년차', width = 2000)
bar_4.use_theme('macarons')
bar_4.add("noon", region, noon_4, yaxis_max=1500, xaxis_rotate = 45)
bar_4.add("night", region, night_4, yaxis_max=1500, xaxis_rotate = -45)

bar_5 = Bar("충전소 한 대당 감당 인구수", '5년차', width = 2000)
bar_5.use_theme('macarons')
bar_5.add("noon", region, noon_5, yaxis_max=1500, xaxis_rotate = -45)
bar_5.add("night", region, night_5, yaxis_max=1500, xaxis_rotate = -45)

timeline = Timeline(is_auto_play=True, timeline_bottom=-20, width = 720, height = 400)
timeline.add(bar_0, '초기')
timeline.add(bar_1, '1년차')
timeline.add(bar_2, '2년차')
timeline.add(bar_3, '3년차')
timeline.add(bar_4, '4년차')
timeline.add(bar_5, '5년차')
timeline.render('충전소 한 대당 감당 인구수.html')

시간대별 충전 부하량

In [110]:
data = pd.read_csv('급속완속_시간대별.csv', encoding='cp949')
rapid = data[data['급속/완속'] == '급속']
rapid = rapid.reset_index(drop = True)
slow = data[data['급속/완속'] == '완속']
slow = slow.reset_index(drop=True)

time = data.columns.to_list()
del time[0:2]

rapid_1 = rapid.iloc[0,2:].to_list()
rapid_2 = rapid.iloc[1,2:].to_list()
rapid_3 = rapid.iloc[2,2:].to_list()
rapid_4 = rapid.iloc[3,2:].to_list()
rapid_5 = rapid.iloc[4,2:].to_list()
rapid_6 = rapid.iloc[5,2:].to_list()
rapid_7 = rapid.iloc[6,2:].to_list()
rapid_8 = rapid.iloc[7,2:].to_list()
rapid_9 = rapid.iloc[8,2:].to_list()
rapid_10 = rapid.iloc[9,2:].to_list()
rapid_11 = rapid.iloc[10,2:].to_list()
rapid_12 = rapid.iloc[11,2:].to_list()

slow_1 = slow.iloc[0,2:].to_list()
slow_2 = slow.iloc[1,2:].to_list()
slow_3 = slow.iloc[2,2:].to_list()
slow_4 = slow.iloc[3,2:].to_list()
slow_5 = slow.iloc[4,2:].to_list()
slow_6 = slow.iloc[5,2:].to_list()
slow_7 = slow.iloc[6,2:].to_list()
slow_8 = slow.iloc[7,2:].to_list()
slow_9 = slow.iloc[8,2:].to_list()
slow_10 = slow.iloc[9,2:].to_list()
slow_11 = slow.iloc[10,2:].to_list()
slow_12 = slow.iloc[11,2:].to_list()

bar_1 = Bar("시간대별 충전 부하량",'1월')
bar_1.use_theme('macarons')
bar_1.add('급속', time, rapid_1, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_1.add('완속', time, slow_1, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_2 = Bar("시간대별 충전 부하량",'2월')
bar_2.use_theme('macarons')
bar_2.add('급속', time, rapid_2, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_2.add('완속', time, slow_2, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_3 = Bar("시간대별 충전 부하량",'3월')
bar_3.use_theme('macarons')
bar_3.add('급속', time, rapid_3, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_3.add('완속', time, slow_3, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_4 = Bar("시간대별 충전 부하량",'4월')
bar_4.use_theme('macarons')
bar_4.add('급속', time, rapid_4, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_4.add('완속', time, slow_4, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_5 = Bar("시간대별 충전 부하량",'5월')
bar_5.use_theme('macarons')
bar_5.add('급속', time, rapid_5, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_5.add('완속', time, slow_5, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_6 = Bar("시간대별 충전 부하량",'6월')
bar_6.use_theme('macarons')
bar_6.add('급속', time, rapid_6, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_6.add('완속', time, slow_6, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_7 = Bar("시간대별 충전 부하량",'7월')
bar_7.use_theme('macarons')
bar_7.add('급속', time, rapid_7, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_7.add('완속', time, slow_7, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_8 = Bar("시간대별 충전 부하량",'8월')
bar_8.use_theme('macarons')
bar_8.add('급속', time, rapid_8, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_8.add('완속', time, slow_8, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_9 = Bar("시간대별 충전 부하량",'9월')
bar_9.use_theme('macarons')
bar_9.add('급속', time, rapid_9, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_9.add('완속', time, slow_9, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_10 = Bar("시간대별 충전 부하량",'10월')
bar_10.use_theme('macarons')
bar_10.add('급속', time, rapid_10, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_10.add('완속', time, slow_10, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_11 = Bar("시간대별 충전 부하량",'11월')
bar_11.use_theme('macarons')
bar_11.add('급속', time, rapid_11, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_11.add('완속', time, slow_11, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

bar_12 = Bar("시간대별 충전 부하량",'12월')
bar_12.use_theme('macarons')
bar_12.add('급속', time, rapid_12, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)
bar_12.add('완속', time, slow_12, is_stack = True, yaxis_max=500000, xaxis_rotate = -45)

timeline = Timeline(is_auto_play=True, timeline_bottom = -5, width = 900)
timeline.add(bar_1, '1월')
timeline.add(bar_2, '2월')
timeline.add(bar_3, '3월')
timeline.add(bar_4, '4월')
timeline.add(bar_5, '5월')
timeline.add(bar_6, '6월')
timeline.add(bar_7, '7월')
timeline.add(bar_8, '8월')
timeline.add(bar_9, '9월')
timeline.add(bar_10, '10월')
timeline.add(bar_11, '11월')
timeline.add(bar_12, '12월')
timeline.render('시간대별 충전 부하량.html')

## 3. 출처

- 고속도로 교통량 http://www.road.re.kr/itms/itms_01.asp
- 자동충전 고속도로 비용 https://www.sciencetimes.co.kr/news/%EC%8A%A4%EC%9B%A8%EB%8D%B4%EC%97%90%EB%8A%94-%EB%8B%AC%EB%A6%AC%EB%A9%B4-%EC%B6%A9%EC%A0%84%EB%90%98%EB%8A%94-%EB%8F%84%EB%A1%9C%EA%B0%80-%EC%9E%88%EB%8B%A4/
- 고속도로 예산 측정 기준 http://www.pmnews.co.kr/103606
- 고속도로 좌표 http://data.ex.co.kr/portal/fdwn/view?type=ETC&num=S0&requestfrom=dataset#

- 전기차 충전소 설치 현황 https://www.data.go.kr/data/15076352/openapi.do
- 전기차 충전소 설치 예산 측정 기준 https://yesan.seoul.go.kr/wk/wkSelect.do?itemId=103679&tr_code=sweb
- 전기차 충전소 가격 측정 기준 https://m.etnews.com/20210117000030
- 서울시 생활인구 http://data.seoul.go.kr/dataList/OA-15439/S/1/datasetView.do
- 전기차 충전소 대 인구 https://www.researchgate.net/figure/Comparison-of-electric-vehicle-charging-infrastructure-per-million-population-in-selected_fig1_320211098
- 시간대별 전기충전소 사용량 https://www.data.go.kr/data/15039553/fileData.do

## 읽어주셔서 감사합니다